<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin-PC" name="test1" tests="2" failures="1" timestamp="29 Oct 2020 08:17:53 GMT" time="0.542" errors="0">
  <testcase name="test1" time="0.504" classname="com.mock.example.service.testngimpl.test1.TestNgMysql">
    <failure type="java.lang.RuntimeException" message="Timed out waiting for the codeBlock to not throw throwable!">
      <![CDATA[java.lang.RuntimeException: Timed out waiting for the codeBlock to not throw throwable!
	at com.mock.constant.teseng.BaseTestNgPrepare.waitForCodeBlockToNotThrowThrowableAndReturnTrue(BaseTestNgPrepare.java:85)
	at com.mock.constant.teseng.BaseTestNgPrepare.waitForCheckoutResult(BaseTestNgPrepare.java:47)
	at com.mock.example.service.testngimpl.test1.TestNgMysql.test1(TestNgMysql.java:12)
Caused by: java.lang.AssertionError: expected [121] but found [12]
	at com.mock.example.service.testngimpl.test1.TestNgMysql.lambda$0(TestNgMysql.java:13)
	at com.mock.constant.teseng.BaseTestNgPrepare.lambda$0(BaseTestNgPrepare.java:48)
	at com.mock.constant.teseng.BaseTestNgPrepare.waitForCodeBlockToNotThrowThrowableAndReturnTrue(BaseTestNgPrepare.java:67)
	... 26 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="testLambda" time="0.003" classname="com.mock.example.service.testngimpl.test1.TestNgMysql"/>
</testsuite> <!-- test1 -->
