<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="690" started-at="2020-10-31T05:23:12Z" finished-at="2020-10-31T05:23:12Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="690" started-at="2020-10-31T05:23:12Z" finished-at="2020-10-31T05:23:12Z">
      <class name="com.mock.example.service.testngimpl.test1.TestNgMysql">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.mock.example.service.testngimpl.test1.TestNgMysql@70a9f84e]" name="beforeSuite" is-config="true" duration-ms="48" started-at="2020-10-31T13:23:12Z" finished-at="2020-10-31T13:23:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.mock.example.service.testngimpl.test1.TestNgMysql@70a9f84e]" name="beforeClass" is-config="true" duration-ms="3" started-at="2020-10-31T13:23:12Z" finished-at="2020-10-31T13:23:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.mock.example.service.testngimpl.test1.TestNgMysql@70a9f84e]" name="test1" duration-ms="592" started-at="2020-10-31T13:23:12Z" finished-at="2020-10-31T13:23:12Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Timed out waiting for the codeBlock to not throw throwable!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Timed out waiting for the codeBlock to not throw throwable!
	at com.mock.constant.teseng.BaseTestNgPrepare.waitForCodeBlockToNotThrowThrowableAndReturnTrue(BaseTestNgPrepare.java:86)
	at com.mock.constant.teseng.BaseTestNgPrepare.waitForCheckoutResult(BaseTestNgPrepare.java:48)
	at com.mock.example.service.testngimpl.test1.TestNgMysql.test1(TestNgMysql.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.AssertionError: expected [121] but found [12]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.mock.example.service.testngimpl.test1.TestNgMysql.lambda$0(TestNgMysql.java:16)
	at com.mock.constant.teseng.BaseTestNgPrepare.lambda$0(BaseTestNgPrepare.java:49)
	at com.mock.constant.teseng.BaseTestNgPrepare.waitForCodeBlockToNotThrowThrowableAndReturnTrue(BaseTestNgPrepare.java:68)
	... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="testLambda()[pri:0, instance:com.mock.example.service.testngimpl.test1.TestNgMysql@70a9f84e]" name="testLambda" duration-ms="9" started-at="2020-10-31T13:23:12Z" finished-at="2020-10-31T13:23:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLambda -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.mock.example.service.testngimpl.test1.TestNgMysql@70a9f84e]" name="afterClass" is-config="true" duration-ms="1" started-at="2020-10-31T13:23:12Z" finished-at="2020-10-31T13:23:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="FAIL" signature="afterSuite()[pri:0, instance:com.mock.example.service.testngimpl.test1.TestNgMysql@70a9f84e]" name="afterSuite" is-config="true" duration-ms="0" started-at="2020-10-31T13:23:13Z" finished-at="2020-10-31T13:23:13Z">
          <exception class="java.lang.ExceptionInInitializerError">
            <full-stacktrace>
              <![CDATA[java.lang.ExceptionInInitializerError
	at com.mock.constant.teseng.BaseTestNg.afterSuite(BaseTestNg.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:336)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown database 'func1'
	at com.mock.utils.forcheck.mysqlutils.MysqlUtils.getConnection(MysqlUtils.java:85)
	at com.mock.utils.forcheck.mysqlutils.MysqlUtils.<clinit>(MysqlUtils.java:29)
	... 19 more
Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'func1'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.mock.utils.forcheck.mysqlutils.MysqlUtils.getConnection(MysqlUtils.java:79)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ExceptionInInitializerError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.mock.example.service.testngimpl.test1.TestNgMysql -->
    </test> <!-- test1 -->
  </suite> <!-- Suite -->
</testng-results>
